notifications:
  email: false

#Install a Terraform executable locally
before_install:
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64.zip

#These two steps will effectively validate our terraform and output a list of any changes to be made to our infrastructure
script:
  - ./terraform init
  - ./terraform plan -target=module.vpc

deploy:
#Roll out any terraform changes required
- provider: script
  script: 
    - ./terraform apply -target=module.vpc
  skip_cleanup: true
  on:
    branch: master

script:
  - ./terraform plan -target=module.ecs

deploy:
#Roll out any terraform changes required
- provider: script
  script: 
    - ./terraform apply -target=module.ecs
  skip_cleanup: true
  on:
    branch: master

script:
  - ./terraform plan -target=module.ec2

deploy:
#Roll out any terraform changes required
- provider: script
  script: 
    - ./terraform apply -target=module.ec2
  skip_cleanup: true
  on:
    branch: master